/* CREATE SCHEMAS */
CREATE SCHEMA IF NOT EXISTS CRAWL;


/* CREATE TABLES */
CREATE TABLE IF NOT EXISTS CRAWL.INFO (
  SEARCH_CODE TEXT,
  SEARCH_TYPE CHAR(3) NOT NULL,
  START_URL TEXT NOT NULL,
  MAX_LEVEL SMALLINT NOT NULL,
  CRAWLED_DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP(0),
  PRIMARY KEY (SEARCH_CODE)
);

CREATE TABLE IF NOT EXISTS CRAWL.DATA (
  SEARCH_CODE TEXT,
  ID CHAR(32),
  URL TEXT NOT NULL,
  LEVEL SMALLINT NOT NULL,
  PARENT_ID CHAR(32),
  PRIMARY KEY (SEARCH_CODE, ID),
  FOREIGN KEY (SEARCH_CODE, PARENT_ID) REFERENCES CRAWL.DATA(SEARCH_CODE, ID),
  FOREIGN KEY (SEARCH_CODE) REFERENCES CRAWL.INFO(SEARCH_CODE)
);
